# Generated by Django 4.1 on 2023-12-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_fabrication',
        ),
    ]
