# Generated by Django 4.1 on 2023-11-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'Ordem', 'verbose_name_plural': 'Ordens'},
        ),
    ]
