# Generated by Django 4.1 on 2023-12-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_password'),
        ('orders', '0003_remove_order_description_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
