# Generated by Django 4.1 on 2023-12-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
