# Generated by Django 4.2.7 on 2023-11-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('phone', models.IntegerField(max_length=18, unique=True, verbose_name='Telefone')),
                ('address', models.CharField(max_length=50, verbose_name='Endereco')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
                'ordering': ['id'],
            },
        ),
    ]
