# Generated by Django 4.2.7 on 2023-12-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='Telefone'),
        ),
    ]
