# Generated by Django 4.1 on 2023-12-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='perfil',
            field=models.CharField(choices=[('a', 'Administrador'), ('c', 'Cliente')], default='c', max_length=1),
        ),
    ]
