# Generated by Django 4.1 on 2023-12-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_perfil_users_profile_remove_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=models.IntegerField(unique=True, verbose_name='Telefone'), max_length=128, verbose_name='Senha'),
        ),
    ]
